title: "Zhuoka Feng"
description: "Personal academic homepage"
url: "https://arkazhuo.github.io"
baseurl: ""
repository: "ArkaZhuo/ArkaZhuo.github.io"

google_scholar_stats_use_cdn: true

author:
  name: "Zhuoka Feng"
  email: "23307130211@m.fudan.edu.cn"
  avatar: "images/profile.jpg"
  university: "Fudan University"
  location: "Shanghai, China"
  github: "ArkaZhuo"
  google_scholar: ""
  linkedin: ""
  orcid: ""
  homepage: ""

exclude:
  - README.md
  - docs/
